### ISSUE TITLE
회원 가입

### ISSUE THREAD

**Issue by KJJ924** [KJJ924/idus#3]
## 유형
- [x] 기능 추가
- [ ] 기능 개선
- [ ] 버그 수정

## 목적
- 회원 가입 구현

## 작업할 내용
- [x] 회원 가입 구현 #4
- [x] 중복 회원 가입 예외처리 #4
- [x] passwordEncoder 설정  #4
- [x]  예외 발생시 테스트코드작성 #7
